### ISSUE TITLE
DHPublicKey expiry time format issue

### ISSUE THREAD

**Issue by rajesha-onemoney** [Sahamati/rahasya#13]
hi @vishwa-vyom ,
  is it mandatory to pass DHPublicKey  expiry time in "2020-09-23T10:53:28.100Z" formate only . 
because we are receiving expiry time from other party while FI Fetch is in the format of "2020-09-23T10:53:28.100+0000".
as per UTC format both are true. so are we accepting both or only Z.  
we are getting below error while passing "2020-09-23T10:53:28.100+0000".
![Screenshot_2020-09-22_17-34-10](https://user-images.githubusercontent.com/69000060/93881489-9b8eb300-fcfc-11ea-9f91-d56aaabd79ad.png)

**Comment by gsasikumar** [comment]
I think we accept only Z as of now. Do you need this implementation? Also if you can add a fix I can accept the PR @rajesha-onemoney

**Comment by gsasikumar** [comment]
@rajesha-onemoney do you still need this or can this be closed?
