### ISSUE TITLE
BAD_DECRYPT 

### ISSUE THREAD

**Issue by ChariKundavarapu** [Sahamati/rahasya#14]
Hi @vishwa-vyom  and @gsasikumar 

Good after noon!

I am trying to decrypt data using key material , but unable to do that because of below exception

"javax.crypto.AEADBadTagException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT"
While calling byte[] cipherData = cipher.doFinal(Base64.getDecoder().decode(base64EncodedData));

Please let me know any changes required.

**Comment by gsasikumar** [comment]
I think we can close this issue. It looks like a wrong data/key during decrypt or the tag was corrupted.
