### ISSUE TITLE
Any support for other language apart from Java?

### ISSUE THREAD

**Issue by sanket-vekariya** [Sahamati/Rahasya#25]
Is there any guidance to implement at mobile side along with all the legal specifications? (Android/iOS/Fluttet/ReactNative or any Web/Mobile Front Technology)

It would be very much helpful if any guidance is available.
Also is there any existing code available or is this under development for user facing languages?
Is there any future plans here to develop with other languages?

**Comment by sanket-vekariya** [comment]
@gsasikumar

**Comment by gsasikumar** [comment]
@sanket-vekariya  I did make some progress but was not able to test this thoroughly. Is it possible to take a look and help me with the test? This has both Javascript and C. The C implementation works till deriving a DHE shared key but not end to end. I feel javascript (node) works end to end.  If you think it's not helping then I can make it in other languages. But rather than doing it in multiple languages, I prefer to have some common language like C or plain old javascript and build the native interfaces in the respective languages.

Can you check the node code to see if it fits your need?
https://github.com/gsasikumar/rahasya/

**Comment by sanket-vekariya** [comment]
@gsasikumar I checked with both the flows.. 
Here are the results.

Javascript (node) output:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/52414184/184081684-37f6f453-2b07-4b0f-9338-81a5faf69efb.png">

C output:

<img width="651" alt="image" src="https://user-images.githubusercontent.com/52414184/184081882-1f211ba0-2a51-464b-8f49-fa4672af3c62.png">

Any guidance how to proceed further along with the flow (encryption for request params, decryption from output result, how to use these keys as an input request of DHPublicKey, etc.) ?

**Comment by gsasikumar** [comment]
@sanket-vekariya  ok got it. Looks like I did it only till deriving the DHE key. we need to use KDF after this. is it possible to include this javascript code in react? If it is then I will create the complete KDF.

**Comment by sanket-vekariya** [comment]
@gsasikumar Sure.. It would be very helpful.. Let us know if anything we can contribute here.

**Comment by sanket-vekariya** [comment]
@gsasikumar Can you update / guide here once this is done? Too many things are depending on this part for us.

**Comment by gsasikumar** [comment]
@sanket-vekariya I have completed the javascript side of the work. I am trying to test it with java to see the compatibility. Will update you soon

**Comment by sanket-vekariya** [comment]
@gsasikumar Sure.. 
If possible, can you please share you WIP code in some branch so we can help you with testing and others??

**Comment by gsasikumar** [comment]
I have committed to the final working code. Feel free to take it from my repo. I will raise the PR soon.

**Comment by sanket-vekariya** [comment]
@gsasikumar This new implementation is based on the "curve25519" as per the AA specifications, correct?

**Comment by gsasikumar** [comment]
@sanket-vekariya if this has addressed your issue then pls close this defect.

**Comment by gsasikumar** [comment]
as this is addressed i am closing this request

**Comment by sriapr98** [comment]
Is there a golang version for this? Can someone share it if they have?
