### ISSUE TITLE
Key Material Discrepancies with ReBIT Spec

### ISSUE THREAD

**Issue by rajesha-onemoney** [Sahamati/rahasya#5]
hi sasikumar,
    i am using the ecc service v1.2 API's via docker. i am able to encrypt the data. while decryption getting below error.
"mac check in GCM failed". actaully we are consuming **ecc** API's in my nodejs application. i am unable to understand this java based error. please help me solve this.

**Envoronment Details:**
OS: Linux
Lang: Node JS

**error response:**
{
    errorCode: 'javax.crypto.AEADBadTagException',
    errorMessage: 'mac check in GCM failed',
    errorInfo: null
  }

**Comment by gsasikumar** [comment]
GCM failed means the data used during encryption and the data after decryption are not matching. 

https://www.cryptosys.net/pki/manpki/pki_aesgcmauthencryption.html

**Comment by rajesha-onemoney** [comment]
Hi Sasi,
 we found below  discrepancies between our keys and ReBIT keys

1. curve value in
   Rebit: Curve25519
   ecc -controller: curve25519

2. key name of DHPublicKey/parmeter
    Rebit: parmeter
   ecc -controller: parameters

3. while encryption you mentioned in text that expecting FI data as *string*
but key name *base64data*

please check the below reference screen shots.


Thanks & Regards,
*A.Rajesh Kumar*
*9666091115*

web*: onemoney.in <https://www.onemoney.in/>*

**Comment by vishwa-vyom** [comment]
@rajesha-onemoney Today we done a new docker release you can get the same using the below pull command.

docker pull gsasikumar/forwardsecrecy:latest

In this build we have taken care of above discrepancy item 1. 

Can you give us more details on discrepancy item 2, since as per V1.1, V1.2 and latest build  DHPublicKey/Parameter is same as  the Rebit spec 1.1.3

Discrepancy item 3 we have still have to fix and I feel this is a valid ask. 

@gsasikumar Please confirm so I can work on this fix.

**Comment by rajesha-onemoney** [comment]
hi @vishwa-vyom ,
please refer below screen shots for  discrepancy item 2.
check keynames of "DHPublicKey" in both images. one is Rebit spec and one is our ecc-service
![Screenshot from 2020-08-17 11-20-20](https://user-images.githubusercontent.com/69000060/90361700-8202a780-e07c-11ea-8f83-1b2c569800d6.png)
![Screenshot from 2020-08-17 11-23-41](https://user-images.githubusercontent.com/69000060/90361721-8cbd3c80-e07c-11ea-883c-14d360990326.png)

**Comment by rajesha-onemoney** [comment]
@vishwa-vyom , @gsasikumar  ?

**Comment by vishwa-vyom** [comment]
@rajesha-onemoney I am current working on the discrepancy item 3, will update back once done..
Also there is pull request for item 2, so once my changes are done will speak to Sasi to merge both and do one more docker release.

**Comment by rajesha-onemoney** [comment]
sure @vishwa-vyom , thanks for the update

**Comment by gsasikumar** [comment]
As this issue is resolved I am closing this issue.
