### ISSUE TITLE
DataProvider Error while generating ECDH

### ISSUE THREAD

**Issue by ChariKundavarapu** [Sahamati/rahasya#6]
Hi Sasikumar,

My Self is Charikundavarapu. I am trying build forwardsecrecy code without Springboot code. I have compiled successfully but while trying  generate ECDH keypair i am getting error. like "no such provider : BC".

I want access utility class file. Currently i am using provider with static value is "BC". Please can you provide which value need to be use in ECCService Class for provider.
![ecdh_provider](https://user-images.githubusercontent.com/68999294/88927675-641fff00-d295-11ea-9a35-e933fc243a86.jpg)

**Comment by gsasikumar** [comment]
Add the security provider.  
`
if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
    Security.addProvider(new BouncyCastleProvider());
}
`

**Comment by ChariKundavarapu** [comment]
Hi SasiKumar,

This is Charikundavarapu from OneMoney. I have raised a ticket on Git repo
regarding getKeyMaterial guidance.
Can you please check and provide the solution for that issue.
I am sharing screen regarding the issue.
