### ISSUE TITLE
ERR java.lang.NullPointerException

### ISSUE THREAD

**Issue by rajesha-onemoney** [Sahamati/rahasya#8]
Hi sasi,
   while trying to decrypt data more than two requests simultaniously i am getting response as "internal server error". while checking  on docker logs we found that is " java.lang.NullPointerException". please guide me resolve it. 
Thanks in advance.

please refer below screen shots
![Screenshot from 2020-08-06 20-28-40](https://user-images.githubusercontent.com/69000060/89547590-9399b300-d823-11ea-82dd-7122d29c8807.png)
![Screenshot from 2020-08-06 20-29-25](https://user-images.githubusercontent.com/69000060/89547709-b6c46280-d823-11ea-979a-b0cc0d462789.png)

**Comment by vishwa-vyom** [comment]
@rajesha-onemoney As per the stacktrace, it looks like issue with base64 encoding of the data. We are trying to reproduce this error but meanwhile can you share the JSON request object that is being sent to the forwardsecrecy service?

**Comment by rajesha-onemoney** [comment]
@vishwa-vyom  actaully we getting issue while trying to decrypt the data of more than 2 FItypes at the same time using for loop. if we are doing with single FI type Data then its decrypting.
the follwing way we are decrytping data

let FIP_DATA={
fi_data:[
{"finshare01":base64 enc data},
{"finshare02":base64 enc data},
{"finshare03":base64 enc data},
],
"keymaterial:{}
} 
we will get data as above from other party which is encrypted using our eccv1.2 only [ present other party also us only]
now we are decrypting the data by iterating the them as loop , so if loop has more than 3 items while decrypting geeting above.
note: keymaterial is same for all

**Comment by vishwa-vyom** [comment]
@rajesha-onemoney When you say for loop, I assume the request for decrypt to forwardsecrecy service is sent one after the other in sequence and not parallel. If you can share us the request JSON for all 3 request of decrypt, we will also try to hardcode and reproduce the issue.

**Comment by rajesha-onemoney** [comment]
Hi @vishwa-vyom  , 
i am providing you the encryption and decryption done around 2hrs back. please check the below attachment. it contains necessary data to decrypt data at our end which is sent by other party. 
[FI_data_enc_N_desc.txt](https://github.com/gsasikumar/forwardsecrecy/files/5040849/FI_data_enc_N_desc.txt)

**Comment by vishwa-vyom** [comment]
Hi @rajesha-onemoney,

I was able to successfully decrypt the data. 

There were 2 encrypted FI data in your txt file, I have put it in a for loop and called the REST API of forwardsecrecy and I got back the decrypted data. I was not able to reproduce the issue.

Please find the decrypted file attached.

[decrypted_data.txt](https://github.com/gsasikumar/forwardsecrecy/files/5042745/decrypted_data.txt)

Please find the below small node js app that I created for validating the same.
[forwardsecrecy_test.zip](https://github.com/gsasikumar/forwardsecrecy/files/5042772/forwardsecrecy_test.zip)

----------

From your stacktrace screenshot, I am suspecting base64YourNonce or base64RemoteNonce in decrypt request could be null in the second request. Can you print the decrypt request body sent to REST API and validate the same?

**Comment by vishwa-vyom** [comment]
@rajesha-onemoney Is your issue resolved?

**Comment by rajesha-onemoney** [comment]
@vishwa-vyom , @gsasikumar  issue resolved. thanks for the support. i am closing this ticket.
